version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
    - dependency-name: k8s.io/*
    - dependency-name: github.com/grpc-ecosystem/*
    - dependency-name: google.golang.org/grpc
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: raw-loader
      - dependency-name: style-loader
      - dependency-name: react-router-dom
      - dependency-name: "@types/react-router-dom"
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /dev/nix
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /sdks/python/client
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/e2e/images/argosay/v1
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/e2e/images/argosay/v2
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /sdks/java/tests
    schedule:
      interval: daily
