name: SDKs
on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  sdks:
    name: Publish SDKs
    if: github.repository == 'argoproj/argo-workflows'
    permissions:
      packages: write # for publishing packages
      contents: write  # for creating releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
        - java
        - python
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - run: make --directory sdks/${{matrix.name}} publish -B
        env:
          JAVA_SDK_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
